"use client";

import { useMemo, useState, type ReactNode } from "react";

type Scenario = "style" | "reorder" | "dad";
type Product = { id:string; brand:string; name:string; price:number; oldPrice?:number; color:string; shape:string; size:string; material:string; tags:string[]; match:string; tone:string };

const products: Product[] = [
  { id:"jj", brand:"John Jacobs", name:"Classic Double Bridge", price:3000, oldPrice:4500, color:"Gold", shape:"Square", size:"M", material:"Stainless steel", tags:["Classic","Square","Medium","Premium"], match:"Classic shape, medium fit", tone:"gold" },
  { id:"vc", brand:"Vincent Chase", name:"Polarized Everyday", price:1200, oldPrice:2000, color:"Black", shape:"Rectangle", size:"M", material:"TR90", tags:["Classic","Lightweight","Medium","Less expensive"], match:"Lightweight and easy to wear", tone:"black" },
  { id:"air", brand:"Lenskart Air", name:"Feather-light Essential", price:1500, oldPrice:2000, color:"Graphite", shape:"Square", size:"M", material:"Ultralight acetate", tags:["Lightweight","Square","Medium","Dad"], match:"Comfortable for long wear", tone:"smoke" },
  { id:"hz", brand:"Hustlr", name:"Bold Street Z", price:800, color:"Crystal black", shape:"Geometric", size:"L", material:"TR90", tags:["Bold","Large","Less expensive"], match:"Strong statement silhouette", tone:"ink" },
  { id:"read", brand:"Lenskart", name:"Reading Ready +1.50", price:800, color:"Brown", shape:"Rectangle", size:"M", material:"Acetate", tags:["Reading","Classic","Medium","Dad"], match:"Ready for near-vision use", tone:"tortoise" },
  { id:"prog", brand:"John Jacobs", name:"Progressive Compatible", price:3000, color:"Gunmetal", shape:"Rectangle", size:"M", material:"Titanium", tags:["Progressive","Classic","Medium","Dad"], match:"Deeper lens height for progressive lenses", tone:"steel" },
];

const copy = {
  style:{ eyebrow:"Explore by style & fit", title:"Nice sunglasses that actually suit you", query:"Nice classic sunglasses that will suit my face", placeholder:"Try “classic sunglasses for me”" },
  reorder:{ eyebrow:"Reorder without risk", title:"Your exact lenses, verified before checkout", query:"Reorder my monthly contact lenses", placeholder:"Try “reorder my monthly contacts”" },
  dad:{ eyebrow:"Shop for someone else", title:"The right glasses for Dad’s actual need", query:"Simple black glasses for my 55-year-old dad", placeholder:"Try “glasses for my dad”" },
};

function Icon({ name, size=20 }:{ name:string; size?:number }) {
  const paths:Record<string,ReactNode> = {
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, mic:<><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"/></>,
    camera:<><path d="M4 7h3l1.5-2h7L17 7h3v12H4z"/><circle cx="12" cy="13" r="3.5"/></>, user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    bag:<><path d="M5 8h14l-1 13H6z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>, heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>,
    arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>, check:<path d="m5 12 4 4L19 6"/>, spark:<><path d="m12 2 1.5 5.5L19 9l-5.5 1.5L12 16l-1.5-5.5L5 9l5.5-1.5z"/><path d="m19 15 .7 2.3L22 18l-2.3.7L19 21l-.7-2.3L16 18l2.3-.7z"/></>,
    tune:<><path d="M4 6h16M7 12h10M10 18h4"/><circle cx="8" cy="6" r="1.5" fill="currentColor"/><circle cx="15" cy="12" r="1.5" fill="currentColor"/><circle cx="12" cy="18" r="1.5" fill="currentColor"/></>, layers:<><rect x="4" y="4" width="16" height="5" rx="2"/><rect x="4" y="11" width="16" height="9" rx="2"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name] || paths.spark}</svg>;
}

function FrameArt({ shape, tone }:{ shape:string; tone:string }) { return <div className={`frame-art ${tone} ${shape.toLowerCase()}`} aria-label={`${shape} eyewear illustration`}><span className="lens left"/><span className="bridge"/><span className="lens right"/><span className="arm left"/><span className="arm right"/></div>; }
function Trace({ n,title,body,accent=false }:{ n:string;title:string;body:string;accent?:boolean }) { return <div className={`trace-step ${accent?"accent":""}`}><span>{n}</span><div><strong>{title}</strong><p>{body}</p></div></div>; }
function Confidence({ label,value }:{ label:string;value:number }) { return <div className="confidence"><div><span>{label}</span><b>{value}%</b></div><div className="meter"><i style={{width:`${value}%`}}/></div></div>; }

function ReorderCard() { return <section className="reorder-card">
  <div className="reorder-visual"><FrameArt shape="Contact" tone="aqua"/><span>30 lenses × 2</span></div>
  <div className="reorder-main"><div className="verified"><Icon name="check" size={15}/> Exact product and prescription match</div><p className="brand">Aqualens</p><h3>24H Monthly Disposable</h3><p className="muted">Your last order · 12 June 2026</p>
    <div className="eye-grid"><div><b>Right eye</b><span>−2.50 SPH</span></div><div><b>Left eye</b><span>−2.25 SPH</span></div><div><b>Base curve</b><span>8.6</span></div><div><b>Diameter</b><span>14.2</span></div></div>
    <div className="safe-note"><Icon name="check" size={17}/><span>Prescription is valid. We never substitute a medically different lens because it “looks similar.”</span></div></div>
  <div className="reorder-buy"><span>Arrives tomorrow</span><h3>₹1,198</h3><p>Gold price · pack of 2</p><button>Reorder exact lenses <Icon name="arrow" size={17}/></button><a>Change quantity or power</a></div>
</section>; }

export default function Home() {
  const [scenario,setScenario] = useState<Scenario>("style"); const [query,setQuery] = useState(copy.style.query); const [preference,setPreference] = useState("Classic"); const [size,setSize] = useState("Medium"); const [inspector,setInspector] = useState(true); const [voice,setVoice] = useState(false); const [why,setWhy] = useState<string|null>(null); const [shortlist,setShortlist] = useState<string[]>([]);
  const ranked = useMemo(() => { const pool=scenario==="dad"?products.filter(p=>p.tags.includes("Dad")):products.filter(p=>!p.tags.includes("Dad")); return [...pool].sort((a,b)=>{ const score=(p:Product)=>(p.tags.includes(preference)?5:0)+(p.tags.includes(size)?3:0)+(preference==="Less expensive"?Math.round((4000-p.price)/400):0); return score(b)-score(a); }); },[scenario,preference,size]);
  function choose(next:Scenario){setScenario(next);setQuery(copy[next].query);setWhy(null);setPreference(next==="dad"?"Reading":"Classic");setSize("Medium")}
  function submit(){const q=query.toLowerCase(); const next:Scenario=q.includes("contact")||q.includes("reorder")||q.includes("monthly")?"reorder":q.includes("dad")||q.includes("father")||q.includes("papa")?"dad":"style";setScenario(next);setWhy(null);setPreference(next==="dad"?"Reading":"Classic");setSize("Medium")}
  const choices=scenario==="dad"?["Reading / phone","Far away","Both","Not sure — eye test"]:["Classic","Lightweight","Bold","Less expensive"]; const chips=scenario==="dad"?["Reading","Progressive","Lightweight","Classic"]:["Classic","Lightweight","Bold","Less expensive"]; const title=copy[scenario];
  return <main>
    <div className="announcement">Free eye test at 2,500+ stores <span>•</span> Next-day delivery in select cities</div>
    <header className="topbar"><a className="logo" href="#"><span className="logo-mark">∞</span>lenskart</a><nav><a>Eyeglasses</a><a>Sunglasses</a><a>Contacts</a><a>Special power</a><a>Stores</a></nav><div className="top-actions"><button aria-label="Wishlist"><Icon name="heart"/></button><button aria-label="Bag"><Icon name="bag"/></button><button aria-label="Profile"><Icon name="user"/></button></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><Icon name="spark" size={17}/> {title.eyebrow}</p><h1>{title.title}</h1><p className="hero-sub">Describe the outcome in your own words. Search will translate it into products, explain trade-offs, and ask only when the answer changes.</p></div><div className="hero-art"><div className="portrait"><span className="face"/><FrameArt shape="Square" tone="ink"/></div><div className="float-card"><small>Decision search</small><b>Goal → constraints → best next step</b></div></div></section>
    <section className="search-stage"><div className="journey-header"><div><p>COMPLETE INTERACTIVE PROTOTYPE</p><h2>Explore all three search journeys</h2></div><span>Choose a journey below—the customer experience and system view update together.</span></div><div className="scenario-tabs" role="tablist"><button className={scenario==="style"?"active":""} onClick={()=>choose("style")}><span>01</span><div><b>I need help choosing</b><small>Style and fit discovery</small></div></button><button className={scenario==="reorder"?"active":""} onClick={()=>choose("reorder")}><span>02</span><div><b>Reorder exact lenses</b><small>Safety-critical exact match</small></div></button><button className={scenario==="dad"?"active":""} onClick={()=>choose("dad")}><span>03</span><div><b>Shopping for Dad</b><small>Proxy purchase and education</small></div></button></div>
      <div className="search-shell"><Icon name="search" size={25}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder={title.placeholder}/><button className={voice?"voice active":"voice"} onClick={()=>setVoice(!voice)} aria-label="Voice search"><Icon name="mic"/></button><button className="camera" aria-label="Search by image"><Icon name="camera"/></button><button className="search-button" onClick={submit}>Search</button></div>
      {voice&&<div className="voice-strip"><span className="wave">||||||||||||</span><b>Listening…</b><span>Say what you need, naturally.</span><button onClick={()=>setVoice(false)}>Done</button></div>}
      <div className="query-tokens"><span>Understood as</span>{scenario==="style"&&<><b>Sunglasses</b><b>For me</b><b>Classic</b><b>Face-suitable</b></>}{scenario==="dad"&&<><b>Eyeglasses</b><b>For Dad</b><b>Age 55</b><b>Simple + black</b></>}{scenario==="reorder"&&<><b>Contacts</b><b>Exact reorder</b><b>Monthly</b><b>Prescription-safe</b></>}<button onClick={()=>setInspector(!inspector)}><Icon name="layers" size={16}/>{inspector?"Hide":"Show"} system view</button></div>
    </section>
    <div className={`experience-grid ${inspector?"with-inspector":""}`}><div className="customer-view">
      {scenario!=="reorder"&&<section className="question-card"><div><p className="step-label">ONE USEFUL QUESTION</p><h2>{scenario==="dad"?"What does your dad need help seeing?":"Which direction feels most like you?"}</h2><p>{scenario==="dad"?"This changes the lens recommendation. Choose frames before adding a prescription.":"Tap once. You can always change it from the results."}</p></div><div className="choice-row">{choices.map(c=><button key={c} className={preference===c||(c.startsWith("Reading")&&preference==="Reading")?"selected":""} onClick={()=>setPreference(c.startsWith("Reading")?"Reading":c)}><span>{c==="Classic"?"◎":c==="Lightweight"?"◌":c==="Bold"?"◇":c==="Less expensive"?"₹":c.startsWith("Reading")?"Aa":c==="Both"?"↕":"?"}</span>{c}</button>)}</div></section>}
      {scenario==="dad"&&<section className="education"><div className="edu-icon">Aa</div><div><b>{preference==="Progressive"||preference==="Both"?"Progressive lenses combine near and distance vision":"Reading glasses help with close-up vision"}</b><p>Choose a compatible frame now. Prescription entry or an eye test can happen later, before checkout.</p></div><button>Learn in 30 sec</button></section>}
      {scenario==="reorder"?<ReorderCard/>:<><div className="results-head"><div><p>{ranked.length*9}+ RESULTS</p><h2>{scenario==="dad"?"Best starting points for Dad":"A smaller, smarter shelf"}</h2></div><div className="size-control"><span>Fit</span>{["Small","Medium","Large"].map(s=><button key={s} className={size===s?"active":""} onClick={()=>setSize(s)}>{s[0]}</button>)}</div></div>
      <div className="product-grid">{ranked.map((p,i)=><article className="product-card" key={p.id}><div className="product-image"><span className="rank">{i===0?"Best match":i===1?"Great alternative":"More choice"}</span><button aria-label="Save" className={`heart ${shortlist.includes(p.id)?"saved":""}`} onClick={()=>setShortlist(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}><Icon name="heart" size={19}/></button><FrameArt shape={p.shape} tone={p.tone}/><button className="try">⌾ Try on face</button></div><div className="product-body"><p className="brand">{p.brand}</p><h3>{p.name}</h3><p className="spec">{p.color} · {p.shape} · {p.size} · {p.material}</p><div className="price"><b>₹{p.price.toLocaleString("en-IN")}</b>{p.oldPrice&&<s>₹{p.oldPrice.toLocaleString("en-IN")}</s>}</div><button className="why" onClick={()=>setWhy(why===p.id?null:p.id)}><Icon name="spark" size={15}/> Why this matches you</button>{why===p.id&&<div className="why-detail">{p.match}. It survives your <b>{size.toLowerCase()} fit</b> constraint.</div>}</div></article>)}</div>
      <div className="refine-bar"><div><Icon name="tune"/><span><b>This, but…</b><small>Refine without starting over</small></span></div><div className="refine-chips">{chips.map(c=><button key={c} className={preference===c?"active":""} onClick={()=>setPreference(c)}>{c}</button>)}</div><button className="more">Show more options <Icon name="arrow" size={16}/></button></div></>}
    </div>
    {inspector&&<aside className="inspector"><div className="inspector-head"><span><Icon name="layers" size={18}/></span><div><p>LIVE SYSTEM VIEW</p><h2>Why these results?</h2></div></div><Trace n="01" title="Typed understanding" body={scenario==="style"?"Goal: style discovery · Subject: self · Constraints: classic, suitable":scenario==="dad"?"Goal: proxy purchase · Subject: Dad · Need: unresolved vision use":"Goal: exact reorder · Medical parameters must match"}/><div className="confidence-wrap"><p>CONFIDENCE IS A VECTOR</p><Confidence label="Product type" value={scenario==="dad"?88:98}/><Confidence label="Vision need" value={scenario==="style"?34:94}/><Confidence label="Style / fit" value={scenario==="reorder"?22:72}/></div><Trace n="02" title="Parallel retrieval" body={scenario==="reorder"?"Order history + exact SKU + prescription validity":"Lexical match + semantic intent + catalogue attributes + profile evidence"}/><Trace n="03" title="Response policy" body={scenario==="reorder"?"Execute when identity and parameters are verified":"Ask one question only when its expected value exceeds friction cost"} accent/><Trace n="04" title="Constraint survival audit" body={scenario==="dad"?"Do not infer prescription from age. Preserve wearer, need and fit through ranking.":scenario==="reorder"?"Exact-match retrieval outranks semantic similarity. No unsafe substitution.":"Preserve classic, medium fit and price preference through reranking."}/><div className="formula"><span>Final score</span><code>relevance + preference + fit + availability − risk</code></div><div className="inspector-foot"><Icon name="check" size={17}/><span>Every explanation comes from evidence used by ranking.</span></div></aside>}
    </div>
  </main>;
}
